dbt_project:
  target: bigquery_dev
  outputs:
    bigquery_dev:
      dataset: analytics
      job_execution_timeout_seconds: 200
      job_retries: 1
      keyfile: ../gcp_creds.json
      location: US
      method: service-account
      priority: interactive
      project: develop-291715
      threads: 4
      type: bigquery